service: node-aws-lambda-crud
frameworkVersion: '2 || 3'

# 람다배포시 package에서 제외
package:
  exclude:
    - node_modules/**
    - package.json
    - package-lock.json

provider:
  name: aws
  runtime: nodejs16.x
   # Version of hashing algorithm used by Serverless Framework for function packaging
  lambdaHashingVersion: '20201221'
  region: ap-northeast-2
  environment:
    #환경변수에 NODE_PATH 설정 node_modules 위치
    NODE_PATH: "./:/opt/node_modules"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: 
        - arn:aws:dynamodb:ap-northeast-2:897982041490:table/Dynamoose-Table 

functions:
  tasks:
    handler: services/Tasks.Tasks
    layers:
      - arn:aws:lambda:ap-northeast-2:897982041490:layer:NodeDataStreamUtils:latest
    events:
      - http: #create
          path: /tasks
          method: post
      - http: #getalltasks
          path: /tasks
          method: get
      - http: #get task by ids
          path: /tasksbyids
          method: get
      - http: #update
          path: /tasks/{id}
          method: put
      - http: #delete by id
          path: /tasks
          method: delete


resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Dynamoose-Table
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
plugins:
  - serverless-offline
  - serverless-latest-layer-version